### ISSUE TITLE
parallelized run time

### ISSUE THREAD

**Issue by johannesnicolaus** [snikumbh/seqArchR#3]
Hi, I was trying to run `seqArchR` for around 12k regions of 80bp using the parameters on the vignettes, setting the cores to 64. I left it running for 3 hours but did not finish, so I thought maybe there is something wrong. When I turned off parallelization, it works but runs slowly, maybe around 1-2 min for each chunk. Is this normal?

**Comment by johannesnicolaus** [comment]
For some reason after I restarted R, now it didn't get stuck and is running much faster with parallelization. I will keep you updated if I come across the same problem again. Please close the issue if you think this is not a bug

**Comment by snikumbh** [comment]
Hi @johannesnicolaus,

Thanks for reporting. Glad that restarting helped! 
Sometimes restarting R frees up memory that can make processing/handling large objects easier. This may have been the case here.
